table 'Limites provisórios'
	lineageTag: cc462e3f-1195-41e1-9a30-b13a4f7c03a9

	column 'Orgãos Código'
		dataType: string
		lineageTag: 60eefc35-00b3-47b8-8b5d-b6f58042cd16
		summarizeBy: none
		sourceColumn: Orgãos Código

		annotation SummarizationSetBy = Automatic

	column 'Orgãos Nome'
		dataType: string
		lineageTag: 88605117-e92b-476c-8819-c876c99cd252
		summarizeBy: none
		sourceColumn: Orgãos Nome

		annotation SummarizationSetBy = Automatic

	column Anexo
		dataType: string
		lineageTag: 89dde707-cf05-46d7-8a7a-8248478c48c1
		summarizeBy: none
		sourceColumn: Anexo

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 24343f21-6fd4-42ef-8f87-0cb5ecd3226e
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Mes
		dataType: string
		lineageTag: ecec4bad-9c61-4c80-8e72-7f41250ddf76
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	partition 'Limites provisórios' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\cruzeiro.stn.intra\Dados_ANALITICOS\DADOS-DAS-AREAS\COFIN\DPOF\Limites longo.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Orgãos Código", type text}, {"Orgãos Nome", type text}, {"Anexo", type text}, {"Valor", type number}, {"Mes", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

