CREATE TABLE [dbo].[DIM_FONTE_RECURSO] (

	[CO_GRUPO_FONTE_RECURSO_DECRETO] varchar(8000) NULL, 
	[SN_FONTE_VINCULADA] decimal(38,6) NULL, 
	[SN_ABERTURA_FONTE] decimal(38,6) NULL, 
	[TX_OBSERVACAO_RELATORIO] varchar(8000) NULL, 
	[CO_FONTE_RECURSO] varchar(8000) NULL, 
	[NO_FONTE_RECURSO] varchar(8000) NULL, 
	[DT_CRIACAO] datetime2(6) NULL
);