CREATE TABLE [dbo].[DIM_ORGAO_DECRETO] (

	[ID_ORGAO_DECRETO_SK] decimal(38,6) NULL, 
	[CO_ORGAO_DECRETO] varchar(8000) NULL, 
	[NO_ORGAO_DECRETO_ABREVIADO] varchar(8000) NULL, 
	[NO_ORGAO_DECRETO] varchar(8000) NULL, 
	[DT_ATUALIZACAO] datetime2(6) NULL, 
	[AN_EXERCICIO] decimal(38,6) NULL, 
	[CO_NO_ORGAO_DECRETO_ABREV] varchar(8000) NULL
);