CREATE TABLE [dbo].[DIM_MARCA_CLASSIFICACAO] (

	[ID_MARCA_CLASSIFICACAO_SK] decimal(38,6) NULL, 
	[NO_MARCA_CLASSIFICACAO] varchar(8000) NULL, 
	[IN_MARCA_CLASSIFICACAO] varchar(8000) NULL, 
	[NO_MARCA_PUBLICACAO] varchar(8000) NULL, 
	[IN_GRUPO_MENSAGEM_SOTN] decimal(38,6) NULL, 
	[NR_PRIORIDADE] decimal(38,6) NULL, 
	[IN_TIPO_LANCAMENTO_SUBCONTA] varchar(8000) NULL, 
	[IN_TIPO_LANCAMENTO_SUBCON_DEST] varchar(8000) NULL, 
	[SN_PRIMARIO] decimal(38,6) NULL
);