CREATE TABLE [dbo].[DIM_ANEXO_DECRETO_DESP] (

	[IS_ANEXO_DECRETO_DESP] decimal(38,6) NULL, 
	[ID_ANEXO_DECRETO_SK] decimal(38,6) NULL, 
	[NO_ANEXO_DECRETO] varchar(8000) NULL, 
	[NR_ORDEM_ANEXO] varchar(8000) NULL, 
	[NO_FORMATADO] varchar(8000) NULL, 
	[DS_ANEXO_DECRETO] varchar(8000) NULL, 
	[IN_TIPO_ANEXO] decimal(38,6) NULL, 
	[AN_EXERCICIO] decimal(38,6) NULL, 
	[IN_TIPO_LIMITE] varchar(8000) NULL, 
	[SN_AFETA_LIMITE] decimal(38,6) NULL, 
	[ID_MARCA_CLASSIFICACAO_DESP_SK] decimal(38,6) NULL, 
	[ID_MARCA_CLASS_PAGTO_EFET_SK] decimal(38,6) NULL
);