CREATE TABLE [dbo].[FATO_LIMITES_PAGEFET] (

	[ID_PAGAMENTO_EFET_ORG_DEC_SK] decimal(38,6) NULL, 
	[AN_PAGAMENTO_EFETIVO] decimal(38,6) NULL, 
	[ME_PAGAMENTO_EFETIVO] decimal(38,6) NULL, 
	[ID_ORGAO_DECRETO_SK] decimal(38,6) NULL, 
	[ID_ANEXO_DECRETO_SK] decimal(38,6) NULL, 
	[VA_DESPESA_PAGA] decimal(38,6) NULL, 
	[VA_RESTOS_PAGAR] decimal(38,6) NULL, 
	[VA_PAGAMENTO_EFET_ORG_DEC] decimal(38,6) NULL, 
	[VA_TRANSFERENCIA_EXTERIOR] decimal(38,6) NULL, 
	[VA_LIMITE_SAQUE] decimal(38,6) NULL
);