CREATE TABLE [dbo].[FATO_LIMITES] (

	[IN_PERIODO] decimal(38,6) NULL, 
	[VA_VALOR] decimal(38,6) NULL, 
	[VA_ANTERIOR] decimal(38,6) NULL, 
	[VA_VARIACAO] decimal(38,6) NULL, 
	[VA_DESPESA_PAGA] decimal(38,6) NULL, 
	[VA_RESTOS_PAGAR] decimal(38,6) NULL, 
	[VA_PAGAMENTO_EFET_ORG_DEC] decimal(38,6) NULL, 
	[VA_TRANSFERENCIA_EXTERIOR] decimal(38,6) NULL, 
	[DT_ATO] datetime2(6) NULL, 
	[ID_LIMITE_EMPENHO_PAGTO_SK] decimal(38,6) NULL, 
	[ID_LIMITE_EMPENHO_PAGTO_VAL_SK] decimal(38,6) NULL, 
	[ID_ORGAO_DECRETO_SK] decimal(38,6) NULL, 
	[ID_ANEXO_DECRETO_SK] decimal(38,6) NULL, 
	[ID_INSTRUMENTO_LEGAL_LIMITE_SK] decimal(38,6) NULL, 
	[SN_VIGENTE] varchar(8000) NULL
);